export const CONTACT_INFO = {
  // Ubicación
  LOCATION: {
    LATITUDE: 11.2662911, // Ejemplo: Ciudad de México
    LONGITUDE: -74.1901212,
    ADDRESS: "Carrera 2 # 17 - 46 Esquina, Taganga, Santa Marta, Magdalena",
  },

  // Información de contacto
  EMAIL: "oceano@oceanoscuba.com.co",
  PHONE: "+57 316 534 1834",

  GOOGLE_MAPS:
    "https://www.google.com/maps/place/Oceano+Scuba+Dive+Center/@11.2660754,-74.1901323,20z/data=!4m5!3m4!1s0x8ef4f530ed242ec1:0x70f7e43977bed39e!8m2!3d11.2662911!4d-74.1901212",

  // Iniciar sesión
  LOGIN: "https://panel.makerstech.co/",

  // Redes sociales
  SOCIAL_MEDIA: {
    TRIPADVISOR:
      "https://www.tripadvisor.co/Attraction_Review-g1149024-d3533901-Reviews-Oceano_Scuba_Dive_Center-Taganga_Santa_Marta_Municipality_Magdalena_Department.html",
    INSTAGRAM: "https://www.instagram.com/oceanoscuba/",
    FACEBOOK: "https://www.facebook.com/OceanoScuba/",
    FLICKR: "https://www.flickr.com/photos/148572699@N03/",
    WHATSAPP:
      "https://api.whatsapp.com/send/?phone=573165341834&text=Hello%2C+¿Podrías+ayudarme%3F+&type=phone_number&app_absent=0",
  },
};

export const ROUTES = {
  HOME: "/",
  ABOUT: "/about-us",
  COURSES: "/courses",
  CONTACT: "/contact",
  LOGIN: "https://panelscuba.makerstech.co/",
  LOCATION: "https://maps.app.goo.gl/H894i4a2vrtyvnDZ6",
} as const;

export const countries = [
  { value: 'AF', label: 'Afganistán' },
  { value: 'AL', label: 'Albania' },
  { value: 'DE', label: 'Alemania' },
  { value: 'AD', label: 'Andorra' },
  { value: 'AO', label: 'Angola' },
  { value: 'AI', label: 'Anguila' },
  { value: 'AQ', label: 'Antártida' },
  { value: 'AG', label: 'Antigua y Barbuda' },
  { value: 'SA', label: 'Arabia Saudita' },
  { value: 'DZ', label: 'Argelia' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AM', label: 'Armenia' },
  { value: 'AW', label: 'Aruba' },
  { value: 'AU', label: 'Australia' },
  { value: 'AT', label: 'Austria' },
  { value: 'AZ', label: 'Azerbaiyán' },
  { value: 'BS', label: 'Bahamas' },
  { value: 'BH', label: 'Bahrein' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BB', label: 'Barbados' },
  { value: 'BE', label: 'Bélgica' },
  { value: 'BZ', label: 'Belice' },
  { value: 'BJ', label: 'Benin' },
  { value: 'BM', label: 'Bermudas' },
  { value: 'BY', label: 'Bielorrusia' },
  { value: 'BO', label: 'Bolivia' },
  { value: 'BQ', label: 'Bonaire, San Eustaquio y Saba' },
  { value: 'BA', label: 'Bosnia y Herzegovina' },
  { value: 'BW', label: 'Botswana' },
  { value: 'BR', label: 'Brasil' },
  { value: 'BN', label: 'Brunei' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'BF', label: 'Burkina Faso' },
  { value: 'BI', label: 'Burundi' },
  { value: 'BT', label: 'Bután' },
  { value: 'CV', label: 'Cabo Verde' },
  { value: 'KH', label: 'Camboya' },
  { value: 'CM', label: 'Camerún' },
  { value: 'CA', label: 'Canadá' },
  { value: 'TD', label: 'Chad' },
  { value: 'CL', label: 'Chile' },
  { value: 'CN', label: 'China' },
  { value: 'CY', label: 'Chipre' },
  { value: 'VA', label: 'Ciudad del Vaticano' },
  { value: 'CO', label: 'Colombia' },
  { value: 'KM', label: 'Comoras' },
  { value: 'CG', label: 'Congo' },
  { value: 'CD', label: 'Congo (Rep. Dem.)' },
  { value: 'KP', label: 'Corea del Norte' },
  { value: 'KR', label: 'Corea del Sur' },
  { value: 'CI', label: 'Costa de Marfil' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'HR', label: 'Croacia' },
  { value: 'CU', label: 'Cuba' },
  { value: 'CW', label: 'Curazao' },
  { value: 'DK', label: 'Dinamarca' },
  { value: 'DJ', label: 'Djibouti' },
  { value: 'DM', label: 'Dominica' },
  { value: 'EC', label: 'Ecuador' },
  { value: 'EG', label: 'Egipto' },
  { value: 'SV', label: 'El Salvador' },
  { value: 'AE', label: 'Emiratos Árabes Unidos' },
  { value: 'ER', label: 'Eritrea' },
  { value: 'SK', label: 'Eslovaquia' },
  { value: 'SI', label: 'Eslovenia' },
  { value: 'ES', label: 'España' },
  { value: 'US', label: 'Estados Unidos' },
  { value: 'EE', label: 'Estonia' },
  { value: 'ET', label: 'Etiopía' },
  { value: 'FJ', label: 'Fiji' },
  { value: 'PH', label: 'Filipinas' },
  { value: 'FI', label: 'Finlandia' },
  { value: 'FR', label: 'Francia' },
  { value: 'GA', label: 'Gabón' },
  { value: 'GM', label: 'Gambia' },
  { value: 'GE', label: 'Georgia' },
  { value: 'GH', label: 'Ghana' },
  { value: 'GI', label: 'Gibraltar' },
  { value: 'GD', label: 'Granada' },
  { value: 'GR', label: 'Grecia' },
  { value: 'GL', label: 'Groenlandia' },
  { value: 'GP', label: 'Guadalupe' },
  { value: 'GU', label: 'Guam' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'GF', label: 'Guayana Francesa' },
  { value: 'GG', label: 'Guernsey' },
  { value: 'GN', label: 'Guinea' },
  { value: 'GQ', label: 'Guinea Ecuatorial' },
  { value: 'GW', label: 'Guinea-Bissau' },
  { value: 'GY', label: 'Guyana' },
  { value: 'HT', label: 'Haití' },
  { value: 'HN', label: 'Honduras' },
  { value: 'HK', label: 'Hong Kong' },
  { value: 'HU', label: 'Hungría' },
  { value: 'IN', label: 'India' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IR', label: 'Irán' },
  { value: 'IQ', label: 'Iraq' },
  { value: 'IE', label: 'Irlanda' },
  { value: 'BV', label: 'Isla Bouvet' },
  { value: 'IM', label: 'Isla de Man' },
  { value: 'CX', label: 'Isla de Navidad' },
  { value: 'NF', label: 'Isla Norfolk' },
  { value: 'IS', label: 'Islandia' },
  { value: 'AX', label: 'Islas Aland' },
  { value: 'KY', label: 'Islas Caimán' },
  { value: 'CC', label: 'Islas Cocos' },
  { value: 'CK', label: 'Islas Cook' },
  { value: 'FO', label: 'Islas Feroe' },
  { value: 'GS', label: 'Islas Georgias del Sur y Sandwich del Sur' },
  { value: 'HM', label: 'Islas Heard y McDonald' },
  { value: 'FK', label: 'Islas Malvinas' },
  { value: 'MP', label: 'Islas Marianas del Norte' },
  { value: 'MH', label: 'Islas Marshall' },
  { value: 'PN', label: 'Islas Pitcairn' },
  { value: 'SB', label: 'Islas Salomón' },
  { value: 'TC', label: 'Islas Turcas y Caicos' },
  { value: 'UM', label: 'Islas ultramarinas de Estados Unidos' },
  { value: 'VG', label: 'Islas Vírgenes Británicas' },
  { value: 'VI', label: 'Islas Vírgenes de los Estados Unidos' },
  { value: 'IL', label: 'Israel' },
  { value: 'IT', label: 'Italia' },
  { value: 'JM', label: 'Jamaica' },
  { value: 'JP', label: 'Japón' },
  { value: 'JE', label: 'Jersey' },
  { value: 'JO', label: 'Jordania' },
  { value: 'KZ', label: 'Kazajstán' },
  { value: 'KE', label: 'Kenia' },
  { value: 'KG', label: 'Kirguistán' },
  { value: 'KI', label: 'Kiribati' },
  { value: 'KW', label: 'Kuwait' },
  { value: 'LA', label: 'Laos' },
  { value: 'LS', label: 'Lesotho' },
  { value: 'LV', label: 'Letonia' },
  { value: 'LB', label: 'Líbano' },
  { value: 'LR', label: 'Liberia' },
  { value: 'LY', label: 'Libia' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Lituania' },
  { value: 'LU', label: 'Luxemburgo' },
  { value: 'MO', label: 'Macao' },
  { value: 'MK', label: 'Macedonia del Norte' },
  { value: 'MG', label: 'Madagascar' },
  { value: 'MY', label: 'Malasia' },
  { value: 'MW', label: 'Malawi' },
  { value: 'MV', label: 'Maldivas' },
  { value: 'ML', label: 'Mali' },
  { value: 'MT', label: 'Malta' },
  { value: 'MA', label: 'Marruecos' },
  { value: 'MQ', label: 'Martinica' },
  { value: 'MU', label: 'Mauricio' },
  { value: 'MR', label: 'Mauritania' },
  { value: 'YT', label: 'Mayotte' },
  { value: 'MX', label: 'México' },
  { value: 'FM', label: 'Micronesia' },
  { value: 'MD', label: 'Moldavia' },
  { value: 'MC', label: 'Mónaco' },
  { value: 'MN', label: 'Mongolia' },
  { value: 'ME', label: 'Montenegro' },
  { value: 'MS', label: 'Montserrat' },
  { value: 'MZ', label: 'Mozambique' },
  { value: 'MM', label: 'Myanmar' },
  { value: 'NA', label: 'Namibia' },
  { value: 'NR', label: 'Nauru' },
  { value: 'NP', label: 'Nepal' },
  { value: 'NI', label: 'Nicaragua' },
  { value: 'NE', label: 'Níger' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'NU', label: 'Niue' },
  { value: 'NO', label: 'Noruega' },
  { value: 'NC', label: 'Nueva Caledonia' },
  { value: 'NZ', label: 'Nueva Zelanda' },
  { value: 'OM', label: 'Omán' },
  { value: 'NL', label: 'Países Bajos' },
  { value: 'PK', label: 'Pakistán' },
  { value: 'PW', label: 'Palau' },
  { value: 'PS', label: 'Palestina' },
  { value: 'PA', label: 'Panamá' },
  { value: 'PG', label: 'Papúa Nueva Guinea' },
  { value: 'PY', label: 'Paraguay' },
  { value: 'PE', 'label': 'Perú' },
  { value: 'PF', label: 'Polinesia Francesa' },
  { value: 'PL', label: 'Polonia' },
  { value: 'PT', label: 'Portugal' },
  { value: 'PR', label: 'Puerto Rico' },
  { value: 'QA', label: 'Qatar' },
  { value: 'GB', label: 'Reino Unido' },
  { value: 'CF', label: 'República Centroafricana' },
  { value: 'CZ', label: 'República Checa' },
  { value: 'DO', label: 'República Dominicana' },
  { value: 'RE', label: 'Reunión' },
  { value: 'RW', label: 'Ruanda' },
  { value: 'RO', label: 'Rumania' },
  { value: 'RU', label: 'Rusia' },
  { value: 'EH', label: 'Sahara Occidental' },
  { value: 'WS', label: 'Samoa' },
  { value: 'AS', label: 'Samoa Americana' },
  { value: 'BL', label: 'San Bartolomé' },
  { value: 'KN', label: 'San Cristóbal y Nieves' },
  { value: 'SM', label: 'San Marino' },
  { value: 'MF', label: 'San Martín (Francia)' },
  { value: 'PM', label: 'San Pedro y Miquelón' },
  { value: 'VC', label: 'San Vicente y las Granadinas' },
  { value: 'SH', label: 'Santa Helena' },
  { value: 'LC', label: 'Santa Lucía' },
  { value: 'ST', label: 'Santo Tomé y Príncipe' },
  { value: 'SN', label: 'Senegal' },
  { value: 'RS', label: 'Serbia' },
  { value: 'SC', label: 'Seychelles' },
  { value: 'SL', label: 'Sierra Leona' },
  { value: 'SG', label: 'Singapur' },
  { value: 'SX', label: 'Sint Maarten' },
  { value: 'SY', label: 'Siria' },
  { value: 'SO', label: 'Somalia' },
  { value: 'LK', label: 'Sri Lanka' },
  { value: 'SZ', label: 'Suazilandia' },
  { value: 'ZA', label: 'Sudáfrica' },
  { value: 'SD', label: 'Sudán' },
  { value: 'SS', label: 'Sudán del Sur' },
  { value: 'SE', label: 'Suecia' },
  { value: 'CH', label: 'Suiza' },
  { value: 'SR', label: 'Surinam' },
  { value: 'SJ', label: 'Svalbard y Jan Mayen' },
  { value: 'TH', label: 'Tailandia' },
  { value: 'TW', label: 'Taiwán' },
  { value: 'TZ', label: 'Tanzania' },
  { value: 'TJ', label: 'Tayikistán' },
  { value: 'IO', label: 'Territorio Británico del Océano Índico' },
  { value: 'TF', label: 'Territorios Australes Franceses' },
  { value: 'TL', label: 'Timor-Leste' },
  { value: 'TG', label: 'Togo' },
  { value: 'TK', label: 'Tokelau' },
  { value: 'TO', label: 'Tonga' },
  { value: 'TT', label: 'Trinidad y Tobago' },
  { value: 'TN', label: 'Túnez' },
  { value: 'TM', label: 'Turkmenistán' },
  { value: 'TR', label: 'Turquía' },
  { value: 'TV', label: 'Tuvalu' },
  { value: 'UA', label: 'Ucrania' },
  { value: 'UG', label: 'Uganda' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'UZ', label: 'Uzbekistán' },
  { value: 'VU', label: 'Vanuatu' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Vietnam' },
  { value: 'WF', label: 'Wallis y Futuna' },
  { value: 'YE', label: 'Yemen' },
  { value: 'ZM', label: 'Zambia' },
  { value: 'ZW', label: 'Zimbabue' },
];
